apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ashudep1
  name: ashudep1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ashudep1
  strategy: {}
  template: # to create pod 
    metadata:
      creationTimestamp: null
      labels:
        app: ashudep1
    spec: # put app specifications 
      imagePullSecrets:
      - name: imagesec1
      containers:
      - image: oracleindia.azurecr.io/oracleday3:v1
        name: oracleday3
        ports:
        - containerPort: 80
        env: 
        - name: deploy 
          value: app2 
        resources: {}
status: {}
