apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: kubernetes-dashboard
  annotations:
    kubernetes.io/service-account.name: "kubernetes-dashboard"
type: kubernetes.io/service-account-token
