apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: ashupod1
  name: ashupod1 # name of pod 
spec:
  containers:
  - image: dockerashu/ashuwebapp:v2 # image from docker hub 
    name: ashupod1 # name of container 
    ports: # port of container app
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
