apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ashulb1
  name: ashulb1
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector: # to find pod using label 
    run: ashupod1 # label of my pods 
  type: NodePort
status:
  loadBalancer: {}
